version: "3"
services:
  person_server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TAG=person_server:v1.0
    image: person_server:v1.0
    container_name: person_server
    ports:
      - "3000:3000"
    env_file:
      - .env

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificate.pem:/etc/nginx/certificate.pem
      - ./key.pem:/etc/nginx/key.pem
